parameters:
- name: deploymentScope
  type: string
  default: 'Resource Group'
- name: azureResourceManagerConnection
  type: string
  default: ''
- name: action
  type: string
  default: 'Create Or Update Resource Group'
- name: resourceGroupName
  type: string
  default: ''
- name: location
  type: string
  default: eastus
- name: csmFileLink
  type: string
  default: ''
- name: overrideParameters
  type: string
  default: ''
- name: csmParametersFileLink
  type: string
  default: ''
- name: deploymentMode
  type: string
  default: 'Incremental'


steps:
 - task: AzureResourceManagerTemplateDeployment@3
   inputs:
    deploymentScope: ${{ parameters.deploymentScope }}
    azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
    action: ${{ parameters.action  }}
    resourceGroupName: ${{ parameters.resourceGroupName }}
    location: ${{ parameters.location }}
    csmFileLink: '$(Agent.BuildDirectory)/${{ parameters.csmFileLink }}'
    csmParametersFileLink: '$(Agent.BuildDirectory)/${{ parameters.csmParametersFileLink }}'
    overrideParameters: ${{ parameters.overrideParameters }}
    deploymentMode: ${{ parameters.deploymentMode }}
    templateLocation: 'URL of file'
