parameters:
- name: deploymentScope
  type: string
  default: 'Resource Group'
- name: azureResourceManagerConnection
  type: string
  default: ''
- name: action
  type: string
  default: 'Create Or Update Resource Group'
- name: resourceGroupName
  type: string
  default: ''
- name: location
  type: string
  default: eastus
- name: csmFile
  type: string
  default: ''
- name: overrideParameters
  type: string
  default: ''
- name: csmParametersFile
  type: string
  default: ''
- name: deploymentMode
  type: string
  default: 'Incremental'
- name: templateLocation
  type: string
  default: 'Linked artifact'

steps:
 - task: AzureResourceManagerTemplateDeployment@3
   inputs:
    deploymentScope: ${{ parameters.deploymentScope }}
    azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
    action: ${{ parameters.action  }}
    resourceGroupName: ${{ parameters.resourceGroupName }}
    location: ${{ parameters.location }}
    csmFile: '$(Agent.BuildDirectory)/${{ parameters.csmFile }}'
    csmParametersFile: '$(Agent.BuildDirectory)/${{ parameters.csmParametersFile }}'
    overrideParameters: ${{ parameters.overrideParameters }}
    deploymentMode: ${{ parameters.deploymentMode }}
    templateLocation: ${{ parameters.templateLocation }}
