parameters:
- name: azureSubscriptionName
  type: string
- name: scriptPath
  type: string
- name: ScriptArguments
  type: string
  default: ''
- name: errorActionPreference
  type: string
  default: 'stop'
- name: FailOnStandardError
  type: boolean
  default: false
- name: azurePowerShellVersion
  type: string
  default: 'azurePowerShellVersion'
- name: preferredAzurePowerShellVersion
  type: string
  default: '3.1.0'
- name: pwsh
  type: boolean
  default: false
- name: workingDirectory
  type: string
- name: displayName
  type: string
  default: 'Running Custom Azure PowerShell script from file'

steps:
- task: AzurePowerShell@5
  displayName: ${{ parameters.displayName }}
  inputs:
    scriptType: 'FilePath'
    ConnectedServiceNameARM: ${{ parameters.azureSubscriptionName }}
    scriptPath: ${{ parameters.scriptPath  }}
    ScriptArguments: ${{ parameters.ScriptArguments }}
    errorActionPreference: ${{ parameters.errorActionPreference }}
    FailOnStandardError: ${{ parameters.FailOnStandardError }}
    azurePowerShellVersion: ${{ parameters.azurePowerShellVersion }}
    preferredAzurePowerShellVersion: ${{ parameters.preferredAzurePowerShellVersion }}
    pwsh: ${{ parameters.pwsh }}
    
    
    
